version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=GestionBibliotheque.settings
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.0
    ports:
      - "27017:27017"
