# Generated by Django 4.2 on 2024-11-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abonne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cin", models.IntegerField(max_length=8)),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("adresse", models.TextField()),
                ("date_inscription", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("auteur", models.CharField(max_length=200)),
                ("date_publication", models.DateField()),
                ("disponibilite", models.BooleanField(default=True)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField()),
                ("date_retour", models.DateField()),
                (
                    "statut_emprunt",
                    models.CharField(
                        choices=[("En cours", "En cours"), ("Terminé", "Terminé")],
                        max_length=50,
                    ),
                ),
                (
                    "abonne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BibliothequeApp.abonne",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BibliothequeApp.document",
                    ),
                ),
            ],
        ),
    ]
