# Generated by Django 4.2 on 2024-11-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BibliothequeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonne", name="cin", field=models.IntegerField(),
        ),
    ]
